databases:
  - name: traffic_db
    databaseName: traffic_app
    user: traffic_user
    plan: free

services:
  - type: web
    name: traffic_app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        fromDatabase:
          name: traffic_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
